// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLK1tAa61E9elkYB5SKmqzffRkmcdNe9A',
    appId: '1:1045161038439:android:7420bd8e5bddaa3f1fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    storageBucket: 'slidesync-1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1xUq31cWLSdS709UpfqjyMZNO8mtUIh0',
    appId: '1:1045161038439:web:febea48b30503b691fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    authDomain: 'slidesync-1.firebaseapp.com',
    storageBucket: 'slidesync-1.firebasestorage.app',
    measurementId: 'G-DESYR96BQ5',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeiU2OMv18I7j8fDvlhSX6SsF2AMd6F2E',
    appId: '1:1045161038439:ios:ddf60ca936fb65681fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    storageBucket: 'slidesync-1.firebasestorage.app',
    androidClientId: '1045161038439-2rsfa16m7dl14s35fglv020i9js1vn4o.apps.googleusercontent.com',
    iosClientId: '1045161038439-t809t0l67bke2pqg1elqtd1avoons1a5.apps.googleusercontent.com',
    iosBundleId: 'com.bubble.slidesync',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeiU2OMv18I7j8fDvlhSX6SsF2AMd6F2E',
    appId: '1:1045161038439:ios:ddf60ca936fb65681fbac2',
    messagingSenderId: '1045161038439',
    projectId: 'slidesync-1',
    storageBucket: 'slidesync-1.firebasestorage.app',
    androidClientId: '1045161038439-2rsfa16m7dl14s35fglv020i9js1vn4o.apps.googleusercontent.com',
    iosClientId: '1045161038439-t809t0l67bke2pqg1elqtd1avoons1a5.apps.googleusercontent.com',
    iosBundleId: 'com.bubble.slidesync',
  );
}
