import 'package:flutter/material.dart';
import 'package:slidesync/shared/styles/theme/app_theme_model.dart';

List<UnifiedThemeModel> defaultUnifiedThemeModels = [
  const UnifiedThemeModel(
    title: 'Default',
    fontFamily: 'Inter',
    // Improved light theme colors
    primary: Color(0xFF5000B8),
    secondary: Colors.teal,
    surface: Color(0xFFE1E1E1),
    onSurface: Color(0xFF1A1A1A),
    background: Color(0xFFF1F1F1),
    onBackground: Color(0xFF1A1A1A),
    altBackgroundPrimary: Color(0xFFE1E1E1),
    altBackgroundSecondary: Color(0xFFE0F2F1),
    onPrimary: Color(0xFFFFFFFF),
    onSecondary: Color(0xFFFFFFFF),
    // Dark theme unchanged
    primaryDark: Color(0xFF7222DA),
    secondaryDark: Color(0xFF26D0CE),
    surfaceDark: Color(0xFF232323),
    onSurfaceDark: Color(0xFFF0F0F0),
    backgroundDark: Color(0xFF121212),
    onBackgroundDark: Color(0xFFF0F0F0),
    altBackgroundPrimaryDark: Color(0xFF2A1F47),
    altBackgroundSecondaryDark: Color(0xFF1A3D39),
    onPrimaryDark: Color(0xFFFFFFFF),
    onSecondaryDark: Color(0xFF000000),
  ),
  const UnifiedThemeModel(
    title: 'Monochrome',
    fontFamily: 'IBM Plex Sans',
    primary: Color(0xFF000000),
    secondary: Color(0xFF6E6E6E),
    surface: Color(0xFFE1E1E1),
    onSurface: Color(0xFF1A1A1A),
    background: Color(0xFFF2F3F4),
    onBackground: Color(0xFF000000),
    altBackgroundPrimary: Color(0xFFE8E8E8),
    altBackgroundSecondary: Color(0xFFF5F5F5),
    onPrimary: Color(0xFFFFFFFF),
    onSecondary: Color(0xFFFFFFFF),
    primaryDark: Color(0xFFE0E0E0),
    secondaryDark: Color(0xFF42A5F5),
    surfaceDark: Color(0xFF232323),
    onSurfaceDark: Color(0xFFF0F0F0),
    backgroundDark: Color(0xFF121212),
    onBackgroundDark: Color(0xFFF5F5F5),
    altBackgroundPrimaryDark: Color(0xFF2C2C2C),
    altBackgroundSecondaryDark: Color(0xFF1A2332),
    onPrimaryDark: Color(0xFF000000),
    onSecondaryDark: Color(0xFF000000),
  ),
const UnifiedThemeModel(
    title: 'Ocean Cream',
    fontFamily: 'Lato',
    primary: Color(0xFF4A9B9A),
    secondary: Color(0xFF39ACAB),
    surface: Color(0xFFDEE9E9),
    onSurface: Color(0xFF2C3E50),
    background: Color(0xFFF8FCFC),
    onBackground: Color(0xFF2C3E50),
    altBackgroundPrimary: Color(0xFFF3FCFB),
    altBackgroundSecondary: Color(0xFFE8F7F6),
    onPrimary: Color(0xFFFFFFFF),
    onSecondary: Color(0xFFFFFFFF),
    primaryDark: Color(0xFF7BC4C3),
    secondaryDark: Color(0xFF9ECFCB),
    surfaceDark: Color(0xFF1A2B2A),
    onSurfaceDark: Color(0xFFE8F4F8),
    backgroundDark: Color(0xFF0F1A1D),
    onBackgroundDark: Color(0xFFE8F4F8),
    altBackgroundPrimaryDark: Color(0xFF162D2E),
    altBackgroundSecondaryDark: Color(0xFF244143),
    onPrimaryDark: Color(0xFF000000),
    onSecondaryDark: Color(0xFF000000),
  ),

  const UnifiedThemeModel(
    title: 'Twilight Academia',
    fontFamily: 'Nunito',
    primary: Color(0xFF5000B8),
    secondary: Color(0xFF42311A),
    surface: Color(0xFFE5E5E5),
    onSurface: Color(0xFF1A1A1A),
    background: Color(0xFFFAF8F5),
    onBackground: Color(0xFF2D2D2D),
    altBackgroundPrimary: Color(0xFFF1EBFF),
    altBackgroundSecondary: Color(0xFFFFF2E6),
    onPrimary: Color(0xFFFFFFFF),
    onSecondary: Color(0xFFFFFFFF),
    primaryDark: Color(0xFF8B6FFF),
    secondaryDark: Color(0xFFE0C8A8),
    surfaceDark: Color(0xFF232323),
    onSurfaceDark: Color(0xFFF0F0F0),
    backgroundDark: Color(0xFF111119),
    onBackgroundDark: Color(0xFFE8E8E8),
    altBackgroundPrimaryDark: Color(0xFF2B2042),
    altBackgroundSecondaryDark: Color(0xFF42311A),
    onPrimaryDark: Color(0xFFFFFFFF),
    onSecondaryDark: Color(0xFF000000),
  ),
];
