import 'package:flutter/material.dart';
import 'package:slidesync/shared/theme/src/app_theme.dart';

List<UnifiedThemeModel> defaultUnifiedThemeModels = [
  const UnifiedThemeModel(
    title: 'Default',
    fontFamily: 'Raleway',
    theme: AppTheme(
      title: 'Default',
      fontFamily: 'Raleway',
      brightness: Brightness.light,
      primary: Color(0xFF5000B8),
      secondary: Colors.teal,
      surface: Color(0xFFE1E1E1),
      onSurface: Color(0xFF1A1A1A),
      background: Color(0xFFF1F1F1),
      onBackground: Color(0xFF1A1A1A),
      altBackgroundPrimary: Color(0xFFE1E1E1),
      altBackgroundSecondary: Color(0xFFE0F2F1),
      onPrimary: Color(0xFFFFFFFF),
      onSecondary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      success: Color(0xFF1B6E3B),
      onSuccess: Color(0xFFFFFFFF),
      outline: Color(0xFFC4C4C4),
      shadow: Color(0xFF000000),
      inverseSurface: Color(0xFF2E2E2E),
      onInverseSurface: Color(0xFFF4F4F4),
    ),
    darkTheme: AppTheme(
      title: 'Default',
      fontFamily: 'Raleway',
      brightness: Brightness.dark,
      primary: Color(0xFF7222DA),
      secondary: Color(0xFF26D0CE),
      surface: Color(0xFF232323),
      onSurface: Color(0xFFF0F0F0),
      background: Color(0xFF121212),
      onBackground: Color(0xFFF0F0F0),
      altBackgroundPrimary: Color(0xFF2A1F47),
      altBackgroundSecondary: Color(0xFF1A3D39),
      onPrimary: Color(0xFFFFFFFF),
      onSecondary: Color(0xFF000000),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      success: Color(0xFF7CDB9F),
      onSuccess: Color(0xFF00391C),
      outline: Color(0xFF4A4A4A),
      shadow: Color(0xFF000000),
      inverseSurface: Color(0xFFF0F0F0),
      onInverseSurface: Color(0xFF2E2E2E),
    ),
    currentBrightness: Brightness.light,
  ),

  const UnifiedThemeModel(
    title: 'Monochrome',
    fontFamily: 'IBM Plex Sans',
    theme: AppTheme(
      title: 'Monochrome',
      fontFamily: 'IBM Plex Sans',
      brightness: Brightness.light,
      primary: Color(0xFF000000),
      secondary: Color(0xFF6E6E6E),
      surface: Color(0xFFE1E1E1),
      onSurface: Color(0xFF1A1A1A),
      background: Color(0xFFF2F3F4),
      onBackground: Color(0xFF000000),
      altBackgroundPrimary: Color(0xFFE8E8E8),
      altBackgroundSecondary: Color(0xFFF5F5F5),
      onPrimary: Color(0xFFFFFFFF),
      onSecondary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      success: Color(0xFF1B6E3B),
      onSuccess: Color(0xFFFFFFFF),
      outline: Color(0xFFCCCCCC),
      shadow: Color(0xFF000000),
      inverseSurface: Color(0xFF1A1A1A),
      onInverseSurface: Color(0xFFF5F5F5),
    ),
    darkTheme: AppTheme(
      title: 'Monochrome',
      fontFamily: 'IBM Plex Sans',
      brightness: Brightness.dark,
      primary: Color(0xFFE0E0E0),
      secondary: Color(0xFF42A5F5),
      surface: Color(0xFF232323),
      onSurface: Color(0xFFF0F0F0),
      background: Color(0xFF121212),
      onBackground: Color(0xFFF5F5F5),
      altBackgroundPrimary: Color(0xFF2C2C2C),
      altBackgroundSecondary: Color(0xFF1A2332),
      onPrimary: Color(0xFF000000),
      onSecondary: Color(0xFF000000),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      success: Color(0xFF7CDB9F),
      onSuccess: Color(0xFF00391C),
      outline: Color(0xFF444444),
      shadow: Color(0xFF000000),
      inverseSurface: Color(0xFFE0E0E0),
      onInverseSurface: Color(0xFF1A1A1A),
    ),
    currentBrightness: Brightness.light,
  ),

  const UnifiedThemeModel(
    title: 'Ocean Cream',
    fontFamily: 'DM Sans',
    theme: AppTheme(
      title: 'Ocean Cream',
      fontFamily: 'DM Sans',
      brightness: Brightness.light,
      primary: Color(0xFF4A9B9A),
      secondary: Color(0xFF39ACAB),
      surface: Color(0xFFDEE9E9),
      onSurface: Color(0xFF2C3E50),
      background: Color(0xFFF8FCFC),
      onBackground: Color(0xFF2C3E50),
      altBackgroundPrimary: Color(0xFFF3FCFB),
      altBackgroundSecondary: Color(0xFFE8F7F6),
      onPrimary: Color(0xFFFFFFFF),
      onSecondary: Color(0xFFFFFFFF),
      error: Color(0xFFB00020),
      onError: Color(0xFFFFFFFF),
      success: Color(0xFF1B7A4A),
      onSuccess: Color(0xFFFFFFFF),
      outline: Color(0xFFB2CECE),
      shadow: Color(0xFF2C3E50),
      inverseSurface: Color(0xFF2C3E50),
      onInverseSurface: Color(0xFFF0FAFA),
    ),
    darkTheme: AppTheme(
      title: 'Ocean Cream',
      fontFamily: 'DM Sans',
      brightness: Brightness.dark,
      primary: Color(0xFF7BC4C3),
      secondary: Color(0xFF9ECFCB),
      surface: Color(0xFF1A2B2A),
      onSurface: Color(0xFFE8F4F8),
      background: Color(0xFF0F1A1D),
      onBackground: Color(0xFFE8F4F8),
      altBackgroundPrimary: Color(0xFF162D2E),
      altBackgroundSecondary: Color(0xFF244143),
      onPrimary: Color(0xFF000000),
      onSecondary: Color(0xFF000000),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      success: Color(0xFF6DDBA0),
      onSuccess: Color(0xFF003822),
      outline: Color(0xFF2E4A4A),
      shadow: Color(0xFF0A1315),
      inverseSurface: Color(0xFFD8EEED),
      onInverseSurface: Color(0xFF162D2E),
    ),
    currentBrightness: Brightness.light,
  ),

  const UnifiedThemeModel(
    title: 'Twilight Academia',
    fontFamily: 'Nunito',
    theme: AppTheme(
      title: 'Twilight Academia',
      fontFamily: 'Nunito',
      brightness: Brightness.light,
      primary: Color(0xFF5000B8),
      secondary: Color(0xFF42311A),
      surface: Color(0xFFE5E5E5),
      onSurface: Color(0xFF1A1A1A),
      background: Color(0xFFFAF8F5),
      onBackground: Color(0xFF2D2D2D),
      altBackgroundPrimary: Color(0xFFF1EBFF),
      altBackgroundSecondary: Color(0xFFFFF2E6),
      onPrimary: Color(0xFFFFFFFF),
      onSecondary: Color(0xFFFFFFFF),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      success: Color(0xFF2D6A4F),
      onSuccess: Color(0xFFFFFFFF),
      outline: Color(0xFFD5CCEE),
      shadow: Color(0xFF1A0040),
      inverseSurface: Color(0xFF2D2040),
      onInverseSurface: Color(0xFFF5F0FF),
    ),
    darkTheme: AppTheme(
      title: 'Twilight Academia',
      fontFamily: 'Nunito',
      brightness: Brightness.dark,
      primary: Color(0xFF8B6FFF),
      secondary: Color(0xFFE0C8A8),
      surface: Color(0xFF232323),
      onSurface: Color(0xFFF0F0F0),
      background: Color(0xFF111119),
      onBackground: Color(0xFFE8E8E8),
      altBackgroundPrimary: Color(0xFF2B2042),
      altBackgroundSecondary: Color(0xFF42311A),
      onPrimary: Color(0xFFFFFFFF),
      onSecondary: Color(0xFF000000),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      success: Color(0xFF85DBA8),
      onSuccess: Color(0xFF003823),
      outline: Color(0xFF3D2F5A),
      shadow: Color(0xFF0A0010),
      inverseSurface: Color(0xFFE8E0FF),
      onInverseSurface: Color(0xFF2B2042),
    ),
    currentBrightness: Brightness.light,
  ),
];
