class DummyCourses {
  static final List<Map<String, dynamic>> dummyCourses = [
    {"courseCode": "MAT 233", "courseTitle": "Mathematical Methods I", "categoriesCount": 5, "progress": 0.48},
    {
      "courseCode": "CSC 213",
      "courseTitle": "Foundations of Sequential Programming",
      "categoriesCount": 6,
      "progress": 0.72,
    },
    {"courseCode": "MAT 221", "courseTitle": "Abstract Algebra I", "categoriesCount": 4, "progress": 0.36},
    {"courseCode": "PHY 201", "courseTitle": "Classical Mechanics", "categoriesCount": 7, "progress": 0.59},
    {"courseCode": "CSC 226", "courseTitle": "Data Structures and Algorithms", "categoriesCount": 8, "progress": 0.81},
    {"courseCode": "STA 210", "courseTitle": "Probability and Statistics", "categoriesCount": 5, "progress": 0.27},
    {"courseCode": "CSC 301", "courseTitle": "Theory of Computation", "categoriesCount": 6, "progress": 0.66},
    {"courseCode": "PHY 211", "courseTitle": "Electromagnetism", "categoriesCount": 6, "progress": 0.45},
    {"courseCode": "CHE 225", "courseTitle": "Organic Chemistry I", "categoriesCount": 7, "progress": 0.38},
    {"courseCode": "CSC 331", "courseTitle": "Operating Systems", "categoriesCount": 8, "progress": 0.55},
    {"courseCode": "MAT 341", "courseTitle": "Complex Analysis", "categoriesCount": 5, "progress": 0.73},
    {"courseCode": "BCH 201", "courseTitle": "General Biochemistry I", "categoriesCount": 6, "progress": 0.29},
    {"courseCode": "CSC 311", "courseTitle": "Database Management Systems", "categoriesCount": 7, "progress": 0.61},
    {"courseCode": "MAT 352", "courseTitle": "Differential Equations", "categoriesCount": 5, "progress": 0.84},
    {"courseCode": "ECO 201", "courseTitle": "Principles of Microeconomics", "categoriesCount": 4, "progress": 0.47},
    {"courseCode": "CSC 441", "courseTitle": "Artificial Intelligence", "categoriesCount": 9, "progress": 0.91},
    {"courseCode": "PHY 321", "courseTitle": "Quantum Mechanics", "categoriesCount": 6, "progress": 0.76},
    {"courseCode": "STA 312", "courseTitle": "Regression Analysis", "categoriesCount": 5, "progress": 0.53},
    {"courseCode": "MEC 201", "courseTitle": "Engineering Mechanics", "categoriesCount": 8, "progress": 0.68},
    {"courseCode": "CSC 411", "courseTitle": "Software Engineering", "categoriesCount": 10, "progress": 0.95},
    {"courseCode": "GEO 215", "courseTitle": "Physical Geography", "categoriesCount": 5, "progress": 0.32},
    {"courseCode": "CSC 322", "courseTitle": "Computer Networks", "categoriesCount": 7, "progress": 0.58},
    {"courseCode": "MAT 463", "courseTitle": "Numerical Analysis", "categoriesCount": 6, "progress": 0.77},
    {"courseCode": "BTY 202", "courseTitle": "Introductory Biotechnology", "categoriesCount": 4, "progress": 0.41},
    {"courseCode": "CHM 331", "courseTitle": "Inorganic Chemistry", "categoriesCount": 7, "progress": 0.63},
    {"courseCode": "CSC 451", "courseTitle": "Compiler Design", "categoriesCount": 8, "progress": 0.89},
    {"courseCode": "PSY 203", "courseTitle": "Developmental Psychology", "categoriesCount": 6, "progress": 0.52},
  ];
}
