name: Flutter Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Firebase Configuration Files
        shell: bash
        run: |
          mkdir -p lib
          mkdir -p android/app
          
          # Use a heredoc to safely write the JSON content
          cat <<EOF > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF
          
          # Use a heredoc for the Dart file as well
          cat <<EOF > lib/firebase_options.dart
          ${{ secrets.FIREBASE_OPTIONS_DART }}
          EOF
        
      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --profile

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: profile-apk
          path: build/app/outputs/flutter-apk/app-profile.apk
          
